### ISSUE TITLE
(Feature) Remove Address functionality.

### ISSUE THREAD

**Issue by Janther** [poanetwork/poa-popa#87] opened 2018-03-20 22:43 UTC
- **What is it?** (leave one option)
    * New `(Feature)` request (i.e. some nice-to-have feature is missing)

- **What feature are you talking about?**

We'll need to add a function to remove an address. On PoPA-side it should also trigger registry, and registry should trigger PoPA in case subject is removing his own address (since this is allowed by ERC780).

This Issue is a to follow up this thread https://github.com/poanetwork/poa-popa/issues/85#issuecomment-374538722 

here is the conversation so far:

@pablofullana @fvictorio:
> Right, we need to consider the removal of an address, which may be triggered from both parties. We could discuss removals on it's own thread since it may be not that trivial.

@Janther:
> Removal of address is a big thing specially since the legislation of the EU gives everybody the right to be digitally "forgotten".
Also, the PoPA dapp should be concerned with confirming addresses so I don't see why would we want triggers for somebody removing their address. That can be done easily though since the registry emits an event with the removal of a claim.

**Comment by fvictorio** [comment] 2018-04-06 18:08
We discussed how to implement this feature to allow users to remove their registered addresses. We propose splitting this feature in stages.

1. Create a page where the user can see the list of physical addresses that they registered, and indicate which ones were already confirmed. This can be done without modifications to the smart contracts.

2. Modify the PoPA contract, adding a method that allows the user to remove an address that they registered. This method should also remove the claim from the ClaimsRegistry.

3. Add a "Remove" button next to each item in the list. This button should call the method implemented in the previous step.

4. (Optional) We should allow "admins" to also be able to remove addresses. This would need some further design, in case it's a desired feature: who can do this? How do they get a list of addresses? Should they be able to see all registered addresses? How do we accomplish this (since mappings cannot be iterated)?

Let us know what you think.

**Comment by phahulin** [comment] 2018-04-06 19:29
I think (4) is not necessary.

**Comment by phahulin** [comment] 2018-04-06 19:34
I agree on 1-3

**Comment by fvictorio** [comment] 2018-04-19 18:24
I think we can close this now.

**Comment by phahulin** [comment] 2018-04-20 08:00
Implemented in https://github.com/poanetwork/poa-popa/pull/100 , https://github.com/poanetwork/poa-popa/pull/101

**Closed as completed by phahulin** 2018-04-20 08:00 UTC
Labels: scope-contract
