### ISSUE TITLE
(Bug) Cant finish the process of the app

### ISSUE THREAD

**Issue by SiddigZeidan** [poanetwork/poa-popa#176] opened 2018-06-04 21:29 UTC
After I fill out all the information (fake info ) and pay the MetaMask fee, I always receive the following screen

![image](https://user-images.githubusercontent.com/4807398/40942650-e43bd3de-681c-11e8-9c66-fa777a4e32d1.png)

**Comment by phahulin** [comment] 2018-06-04 22:57
The reason is that non-existent zip code was used (`123456`)
```
error returned by create_postcard: Error: to.address_zip is not a valid ZIP code or to must be a string
```
so for some reason verification didn't work
https://github.com/poanetwork/poa-popa/blob/master/web-dapp/controllers/prepareRegTx.js#L60

**Comment by fvictorio** [comment] 2018-06-05 19:13
When using a development account in POB, the zip code always has to be "11111" and the address "deliverable".

**Comment by garatortiz** [comment] 2018-06-05 19:16
More info about `address` or `primary line` for test environment: [https://lob.com/docs#us-verification-test-environment](https://lob.com/docs#us-verification-test-environment)

**Comment by phahulin** [comment] 2018-06-09 19:29
When using test API key for the post office service, address verification methods don't work (https://lob.com/docs#us-verification-test-environment)

> The test API key does not perform any verification, automatic correction, or standardization for addresses.

However, when making request to send a postcard, verification is done and addresses with fake data are rejected. To run tests, please use "deliverable" and "11111" as suggested above https://github.com/poanetwork/poa-popa/issues/176#issuecomment-394826988

I'm going to close this because it's not a bug. This would need to be re-checked when final version is deployed and production API key is used.

Error message in UI will be improved a little in #182

**Closed as completed by phahulin** 2018-06-09 19:29 UTC
